openapi: 3.0.3
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://blog-app-1cvw.onrender.com
    description: Production server on Render
paths:
  /tasks/{id}:
    $ref: ./paths/tasks.yaml#/~1tasks~1{id}
components:
  schemas:
    $ref: ./components/schemas.yaml
